import Footer from "@/components/Footer";
import Newsletter from "@/components/Newsletter";
import Store from "@/components/Store";
import EnglishSection from "@/sections/EnglishSection";
import GamingSection from "@/sections/GamingSection";
// import GamingSection from "@/sections/GamingSection";
import HeroSection from "@/sections/HeroSection";
import WomenEmporowement from "@/sections/WomenEmporowement";
import { type NextPage } from "next";
import Head from "next/head";
import dynamic from "next/dynamic";

const DynamicEventsSection = dynamic(() => import("@/sections/EventsSection"), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center overflow-x-hidden bg-black">
        <HeroSection />
        <DynamicEventsSection />
        <EnglishSection />
        <GamingSection />
        <WomenEmporowement />
        <Store />
        <Newsletter />
        <Footer />
      </main>
    </>
  );
};

export default Home;
