import Newsletter from "@/components/Newsletter";
import Store from "@/components/Store";
import EnglishSection from "@/sections/EnglishSection";
import EventsSection from "@/sections/EventsSection";
import GamingSection from "@/sections/GamingSection";
// import GamingSection from "@/sections/GamingSection";
import HeroSection from "@/sections/HeroSection";
import WomenEmporowement from "@/sections/WomenEmporowement";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-black">
        <HeroSection />
        <EventsSection />
        <EnglishSection />
        <GamingSection />
        <WomenEmporowement />
        <Store />
        <Newsletter />
      </main>
    </>
  );
};

export default Home;
